# Generated by Django 5.2.16 on 2026-07-26 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('content', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tone', models.CharField(blank=True, choices=[('professional', 'Professional'), ('casual', 'Casual'), ('technical', 'Technical'), ('inspirational', 'Inspirational'), ('storytelling', 'Storytelling')], max_length=20)),
                ('post_type', models.CharField(blank=True, choices=[('story', 'Story'), ('tip', 'Tip'), ('tutorial', 'Tutorial'), ('opinion', 'Opinion'), ('achievement', 'Achievement'), ('question', 'Question')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['author', 'status', 'scheduled_at'], name='content_pos_author__066f08_idx')],
            },
        ),
    ]
