# Generated by Django 5.2.16 on 2026-07-26 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ai', 'AI'), ('productivity', 'Productivity'), ('career', 'Career'), ('mistakes', 'Mistakes'), ('learnings', 'Learnings'), ('opinions', 'Opinions'), ('tutorials', 'Tutorials')], max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', 'category', 'is_saved'], name='ideas_idea_owner_i_e64a63_idx')],
            },
        ),
    ]
